# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20160914_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='year',
            field=models.IntegerField(help_text='Year of publication.', null=True),
        ),
    ]
