# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20160915_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='data_sources',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='end_material_year',
            field=models.IntegerField(help_text='The year when the data collection ended.', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='start_material_year',
            field=models.IntegerField(help_text='The year when the data collection began.', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='government_or_policy',
            field=models.BooleanField(default=False, help_text='Whether the study is a governament or policy study.'),
        ),
    ]
