# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20160917_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_description',
            field=models.CharField(help_text='Description of the data.', max_length=1024),
        ),
    ]
