# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20160917_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='data_description',
        ),
        migrations.AddField(
            model_name='study',
            name='data_description',
            field=models.TextField(default='1', help_text='Description of the data.'),
            preserve_default=False,
        ),
    ]
