# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20160917_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha3',
            field=models.CharField(default='it', help_text='The three letter country code for this country.', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='study',
            name='analysis_methods',
            field=models.ManyToManyField(help_text='Analysis method(s) of the study.', related_name='anaysis_method_study_set', to='database.Method'),
        ),
        migrations.AlterField(
            model_name='study',
            name='collection_methods',
            field=models.ManyToManyField(help_text='Collection method(s) of the study.', related_name='collection_method_study_set', to='database.Method'),
        ),
        migrations.AlterField(
            model_name='study',
            name='methods',
            field=models.ManyToManyField(help_text='Method(s) of the study.', related_name='study_set', to='database.Method'),
        ),
    ]
