# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20160918_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('label', models.CharField(help_text='Name of the domain.', max_length=255, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(help_text='Name of the parent domain.', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDMCARequest',
            fields=[
                ('code', models.IntegerField(help_text='The ID of the request in Google.', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(help_text='The date of the request.')),
                ('lumen_url', models.CharField(help_text='URL in Lumen of the request.', max_length=511)),
                ('from_abuser', models.BooleanField(help_text='Whether the request came from an abuser.')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDMCARequestDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_count', models.IntegerField(help_text='Number of URLs that have been removed.')),
                ('no_action_count', models.IntegerField(help_text='Number of URLs for which no action was taken.')),
                ('under_review_count', models.IntegerField(help_text='Number of URLs currently under review.')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Domain')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.GoogleDMCARequest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='googledmcarequestdomain',
            unique_together=set([('request', 'domain')]),
        ),
    ]
